file_format: "1"
id: a_dux_trackpad
name: A. Dux
type: shield
url: https://github.com/tapioki/cephalopoda/tree/main/Architeuthis%20dux
requires: [pro_micro]
features:
  - keys
siblings:
  - a_dux_trackpad_left
  - a_dux_trackpad_right
